function Test-OptimizeBuildShort {
	Param([HashTable] $config)

	return [System.Collections.Generic.List[string]]@(
		"-j $($config.build.cores)",
		"platform=$($config.build.platform)",
		"target=$($config.build.target)",
		"arch=$($config.build.architecture)"
		"--config=$($config.build.config)"
	)
}

<# 
	"xml=$($config.tools.xml)"
	"module_etc1_enabled=$($config.media.images.etc1)"
	"module_denoise_enabled=$($config.procedural.denoise)"
	"builtin_squish=$($config.media.images.squish.builtin)"
	"builtin_opus=$($config.media.video.vp9opus.builtin)"
	"module_webm_enabled=$($config.media.video.webm)"
	"module_squish_enabled=$($config.media.images.squish.module)"
	"module_opus_enabled=$($config.media.video.vp9opus.module)"
	"builtin_openssl=$($config.network.ssl.builtin)"
	"module_openssl_enabled=$($config.network.ssl.module)"
#>

function Test-OptimizeBuildTemplate {
	Param([HashTable] $config)

	return [System.Collections.Generic.List[string]]@(
		"optimize=$($config.build.optimize)"
		"debug_symbols=$($config.debug.symbols)"
		"separate_debug_symbols=$($config.debug.separate_symbols)"
		"lto=$($config.build.lto)"
		"tools=$($config.tools.editor)"
		"deprecated=$($config.tools.compatibility)"
		"precision=$($config.game.precision)"
		"brotli=$($config.gui.fonts.brotli.module)"
		"xaudio2=$($config.media.sound.xaudio2)"
		"openxr=$($config.vrar.openxr.support)"
		"tests=$($config.tools.tests)"
		"compiledb=$($config.debug.compiledb)"
		"disable_3d=$($config.world3d.disable)"
		"disable_advanced_gui=$($config.gui.notadvanced)"
		"no_editor_splash=$($config.build.no_splash)"
		"use_precise_math_checks=$($config.debug.precise_math)"
		"builtin_brotli=$($config.gui.fonts.brotli.builtin)"
		"builtin_certs=$($config.network.ssl.builtin)"
		"builtin_embree=$($config.procedural.light.raytrace_embree)"
		"builtin_enet=$($config.network.enet.builtin)"
		"builtin_freetype=$($config.gui.fonts.freetype.builtin)"
		"builtin_msdfgen=$($config.gui.fonts.msdfgen.builtin)"
		"builtin_glslang=$($config.procedural.glslang.builtin)"
		"builtin_graphite=$($config.gui.fonts.graphite.builtin)"
		"builtin_harfbuzz=$($config.gui.fonts.builtin_harfbuzz)"
		"builtin_libtheora=$($config.media.video.theora.builtin)"
		"builtin_libvorbis=$($config.media.video.vp8vorbis.builtin)"
		"builtin_wslay=$($config.network.websocket.builtin)"
		"builtin_miniupnpc=$($config.network.builtin_miniupnpc)"
		"builtin_pcre2=$($config.game.pcre2.builtin)"
		"builtin_pcre2_with_jit=$($config.game.pcre2.jit)"
		"builtin_recastnavigation=$($config.world3d.builtin_recastnavigation)"
		"builtin_rvo2_2d=$($config.game.rvo2.d2)"
		"builtin_rvo2_3d=$($config.game.rvo2.d3)"
		"builtin_xatlas=$($config.world3d.xatlas.builtin)"
		"builtin_zlib=$($config.media.zip.zlib)"
		"builtin_zstd=$($config.media.zip.zstd)"
		"use_mingw=$($config.build.use_mingw)"
		"module_basis_universal_enabled=$($config.world3d.basis_universal)"
		"module_bmp_enabled=$($config.media.images.bitmap)"
		"module_camera_enabled=$($config.vrar.camera)"
		"module_csg_enabled=$($config.world3d.csg)"
		"module_cvtt_enabled=$($config.media.images.cvtt)"
		"module_dds_enabled=$($config.world3d.format.dds)"
		"module_enet_enabled=$($config.network.enet.module)"
		"module_freetype_enabled=$($config.gui.fonts.freetype.module)"
		"module_glslang_enabled=$($config.procedural.glslang.module)"
		"module_gltf_enabled=$($config.world3d.format.gltf)"
		"module_gridmap_enabled=$($config.world3d.gridmap)"
		"module_hdr_enabled=$($config.procedural.light.hdr)"
		"module_jsonrpc_enabled=$($config.network.jsonrpc)"
		"module_lightmapper_rd_enabled=$($config.procedural.light.mapper_rd)"
		"module_mbedtls_enabled=$($config.network.mbedtls)"
		"module_meshoptimizer_enabled=$($config.world3d.meshoptimizer)"
		"module_minimp3_enabled=$($config.media.sound.minimp3)"
		"module_mobile_vr_enabled=$($config.vrar.mobile)"
		"module_mono_enabled=$($config.tools.mono)"
		"module_msdfgen_enabled=$($config.gui.fonts.msdfgen.module)"
		"module_multiplayer_enabled=$($config.network.coop)"
		"module_navigation_enabled=$($config.game.navigation)"
		"module_noise_enabled=$($config.procedural.noise)"
		"module_openxr_enabled=$($config.vrar.openxr.module)"
		"module_raycast_enabled=$($config.game.raycast)"
		"module_regex_enabled=$($config.game.regex)"
		"module_theora_enabled=$($config.media.video.theora.module)"
		"graphite=$($config.gui.fonts.graphite.module)"
		"module_upnp_enabled=$($config.tools.upnp)"
		"module_vhacd_enabled=$($config.world3d.vhacd)"
		"module_vorbis_enabled=$($config.media.video.vp8vorbis.module)"
		"module_webp_enabled=$($config.media.images.webp)"
		"module_webrtc_enabled=$($config.network.webrtc)"
		"module_websocket_enabled=$($config.network.websocket.module)"
		"module_webxr_enabled=$($config.vrar.webxr)"
		"module_xatlas_unwrap_enabled=$($config.world3d.xatlas.module)"
		"module_zip_enabled=$($config.media.zip.support)"
	)
}
